# Generated by Django 5.1.4 on 2025-01-02 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('official_name', models.CharField(max_length=255, null=True)),
                ('keywords_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.keywords')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.keywords')),
                ('tags_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('URL_id', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='search.url')),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('keywords_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.keywords')),
            ],
        ),
    ]
